### ISSUE TITLE
Testsuite fails with Bus Error on Linux sparc64

### ISSUE THREAD

**Issue by glaubitz** [contourpy/contourpy#196]
contourpy was recently uploaded to Debian unstable and was consequently built on sparc64. This architecture is particularly sensitive when it comes to bad alignment, any code with unaligned access causes a `Bus Error`.

Unfortunately, this is also the case for contourpy. The `Bus Error` occurs when the testsuite is run:

```
============================= test session starts ==============================
platform linux -- Python 3.11.1, pytest-7.2.0, pluggy-1.0.0+repack
rootdir: /<<PKGBUILDDIR>>
collected 1186 items

tests/test_codebase.py sss.                                              [  0%]
tests/test_config.py .s.s.s.s.s.s.s.s.sss.s.s.s.s.s.s.s.s                [  3%]
tests/test_constructor.py .............................................. [  7%]
........................................................................ [ 13%]
........................................................................ [ 19%]
........................................................................ [ 25%]
........................................................................ [ 31%]
........................................................................ [ 37%]
........................................................................ [ 43%]
........................................................................ [ 49%]
..                                                                       [ 49%]
tests/test_enum.py ................                                      [ 51%]
tests/test_filled.py ................................................... [ 55%]
........................................................................ [ 61%]
........................................................................ [ 67%]
...............................................................ss....... [ 73%]
.....ssssssssss                                                          [ 75%]
tests/test_lines.py .................................................... [ 79%]
........................................................................ [ 85%]
......................s................................................. [ 91%]
........................ss........                                       [ 94%]
tests/test_misc.py ..                                                    [ 94%]
tests/test_renderer.py Fatal Python error: Bus error

Current thread 0xffff80010002d520 (most recent call first):
  File "/usr/lib/python3/dist-packages/numpy/linalg/linalg.py", line 1063 in eigvals
  File "<__array_function__ internals>", line 180 in eigvals
  File "/usr/lib/python3/dist-packages/numpy/lib/polynomial.py", line 254 in roots
  File "<__array_function__ internals>", line 180 in roots
  File "/usr/lib/python3/dist-packages/matplotlib/bezier.py", line 300 in axis_aligned_extrema
  File "/usr/lib/python3/dist-packages/matplotlib/path.py", line 628 in get_extents
  File "/usr/lib/python3/dist-packages/matplotlib/collections.py", line 403 in draw
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 50 in draw_wrapper
  File "/usr/lib/python3/dist-packages/matplotlib/collections.py", line 990 in draw
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 50 in draw_wrapper
  File "/usr/lib/python3/dist-packages/matplotlib/image.py", line 132 in _draw_list_compositing_images
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 3091 in draw
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 50 in draw_wrapper
  File "/usr/lib/python3/dist-packages/matplotlib/image.py", line 132 in _draw_list_compositing_images
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 2837 in draw
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 50 in draw_wrapper
  File "/usr/lib/python3/dist-packages/matplotlib/artist.py", line 73 in draw_wrapper
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 436 in draw
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 540 in print_png
  File "/usr/lib/python3/dist-packages/matplotlib/_api/deprecation.py", line 415 in wrapper
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 1648 in wrapper
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 2319 in print_figure
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 3046 in savefig
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_contourpy/build/contourpy/util/mpl_renderer.py", line 190 in save_to_buffer
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_contourpy/build/tests/test_renderer.py", line 39 in test_renderer_filled
  File "/usr/lib/python3/dist-packages/_pytest/python.py", line 195 in pytest_pyfunc_call
  File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/python.py", line 1789 in runtest
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 167 in pytest_runtest_call
  File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 260 in <lambda>
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 339 in from_call
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 259 in call_runtest_hook
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 220 in call_and_report
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 131 in runtestprotocol
  File "/usr/lib/python3/dist-packages/_pytest/runner.py", line 112 in pytest_runtest_protocol
  File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 349 in pytest_runtestloop
  File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 324 in _main
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 270 in wrap_session
  File "/usr/lib/python3/dist-packages/_pytest/main.py", line 317 in pytest_cmdline_main
  File "/usr/lib/python3/dist-packages/pluggy/_callers.py", line 39 in _multicall
  File "/usr/lib/python3/dist-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/usr/lib/python3/dist-packages/pluggy/_hooks.py", line 265 in __call__
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 167 in main
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 190 in console_main
  File "/usr/lib/python3/dist-packages/pytest/__main__.py", line 5 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, numpy.linalg.lapack_lite, matplotlib._c_internal_utils, PIL._imaging, matplotlib._path, kiwisolver, matplotlib._image (total: 19)
Bus error
E: pybuild pybuild:386: test: plugin pyproject failed with: exit code=138: cd /<<PKGBUILDDIR>>/.pybuild/cpython3_3.11_contourpy/build; python3.11 -m pytest tests
```

I have not had the time yet to look into the details but will hopefully do so in the following days.

In the meantime, the full build log can be obtained here: https://buildd.debian.org/status/fetch.php?pkg=contourpy&arch=sparc64&ver=1.0.6-2&stamp=1671794890&raw=0

**Comment by ianthomas23** [comment]
@glaubitz Thanks for the traceback. The bus error isn't occurring in the contour calculations but in the rendering of the test images using `matplotlib`. So the problem is the data passed from `contourpy` to `matplotlib`. The clue is in the use of `bezier.py` as `contourpy` produces straight line segments only, not bezier curves, so the problem is in the arrays of `Path` codes (https://matplotlib.org/stable/api/path_api.html) which are arrays of `uint8` that are evidently aligned fine on most architectures but differently on sparc64.

Can you confirm this by running a test that doesn't use `matplotlib`, e.g. `pytest tests/test_lines.py::test_return_by_line_type` should hopefully fail on 2 of the 4 tests without a bus error and it will output the different arrays to confirm it is an alignment issue.

If this is the correct diagnosis then a similar problem will occur when `contourpy` iterates over masked `z` arrays, so it will fail on other tests.

**Comment by glaubitz** [comment]
Thanks for the reply!

I checked out the source from git on the GCC Compile Farm sparc64 machine `gcc202` and tried to run the testsuite which fails with:

```
glaubitz@gcc202:~/contourpy$ python3 setup.py test
/usr/lib/python3/dist-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running test
WARNING: Testing via this command is deprecated and will be removed in a future version. Users looking for a generic test entry point independent of test runner are encouraged to use tox.
running egg_info
writing lib/contourpy.egg-info/PKG-INFO
writing dependency_links to lib/contourpy.egg-info/dependency_links.txt
writing requirements to lib/contourpy.egg-info/requires.txt
writing top-level names to lib/contourpy.egg-info/top_level.txt
reading manifest file 'lib/contourpy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'lib/contourpy.egg-info/SOURCES.txt'
running build_ext
sparc64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python3.10 -c flagcheck.cpp -o flagcheck.o -std=c++17

Bad key text.parse_math in file /usr/share/matplotlib/mpl-data/matplotlibrc, line 303 ('text.parse_math: True  # Use mathtext if there is an even number of unescaped')
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.5.2/matplotlibrc.template
or from the matplotlib source distribution
Traceback (most recent call last):
  File "/home/glaubitz/contourpy/setup.py", line 75, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 224, in run
    self.run_tests()
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 227, in run_tests
    test = unittest.main(
  File "/usr/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python3.10/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib/python3.10/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib/python3.10/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib/python3.10/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib/python3.10/unittest/loader.py", line 405, in _find_tests
    tests, should_recurse = self._find_test_path(
  File "/usr/lib/python3.10/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 57, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/glaubitz/contourpy/tests/util_config.py", line 4, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 880, in <module>
    rcParamsDefault = _rc_params_in_file(
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 814, in _rc_params_in_file
    config[key] = val  # try to convert to proper type or raise
  File "/usr/lib/python3/dist-packages/matplotlib/__init__.py", line 650, in __setitem__
    raise ValueError(f"Key {key}: {ve}") from None
ValueError: Key grid.color: '"' does not look like a color arg
glaubitz@gcc202:~/contourpy$
```

No clue how to fix this as I couldn't find any `matplotlibrc.template` in the matplotlib Github repository.

FWIW, you can get access to these machines as well through the GCC Compile Farm, see: https://gcc.gnu.org/wiki/CompileFarm

**Comment by ianthomas23** [comment]
> glaubitz@gcc202:~/contourpy$ python3 setup.py test
> &lt;snip&gt;
> No clue how to fix this as I couldn't find any `matplotlibrc.template` in the matplotlib Github repository.

This is heading off on a tangent. Use of `python setup.py` is deprecated and won't work following `contourpy`'s switch to using `pyproject.toml` for the project and build configuration. To build from source you need to use `python3 -m pip install .[test]` or equivalent, then separately invoke the test suite using `pytest`. The old `python setup.py` approach worked with `contourpy` 1.0.6 as that was before the switch to `pyproject.toml` but it doesn't work any more.

> FWIW, you can get access to these machines as well through the GCC Compile Farm, see: https://gcc.gnu.org/wiki/CompileFarm

I've applied for access, so I should be able to reproduce and fix the bug myself. You may as well hold off doing anything else on this until I report back.

**Comment by ianthomas23** [comment]
@glaubitz I have access to the GCC Compile Farm, but the `sparc64` machines never seem to be accessible.

Regardless of that I have thought further about the possible failure mode I described above and I've realised it cannot occur. The matplotlib `Path` codes I was talking about are `uint8` so they cannot be misaligned on `sparc64`. Given that, the only call to matplotlib's `bezier.py` just before the bus error occurs in contourpy's `MplRenderer.grid()` function at this line:
```python
ax.scatter(x, y, color=point_color, alpha=alpha, marker='o')
```
where the circular markers are drawn as bezier curves and call `numpy.roots()` to solve a small matrix problem to find the bounding box of those curves. So if my analysis is correct here, what you have is a problem with your build of matplotlib or numpy, not contourpy. You could confirm this by commenting out the `ax.scatter` line above and the test that caused the bus error should no longer do so and the test should fail instead because the output PNG will be different. But the test suite should complete without a crash.

The next experiment to try would be to replace the `ax.scatter` line with
```python
ax.plot(x, y, color=point_color, alpha=alpha, marker='o', lw=0)
```
which generates exactly the same output (on common platforms!) but uses an entirely different code path in C++ rather than the Python code that calls `numpy.root`.

I am going to change the `ax.scatter` to `ax.plot` anyway as I think it is a better option and should be marginally faster.

**Comment by glaubitz** [comment]
> @glaubitz I have access to the GCC Compile Farm, but the `sparc64` machines never seem to be accessible.

There were some hardware issues. At least gcc202 is back online, so you can try to login:

```
glaubitz@gcc202:~$ uname -a
Linux gcc202 5.19.0-2-sparc64-smp #1 SMP Debian 5.19.11-1 (2022-09-24) sparc64 GNU/Linux
glaubitz@gcc202:~$
```

> Regardless of that I have thought further about the possible failure mode I described above and I've realised it cannot occur. The matplotlib `Path` codes I was talking about are `uint8` so they cannot be misaligned on `sparc64`. Given that, the only call to matplotlib's `bezier.py` just before the bus error occurs in contourpy's `MplRenderer.grid()` function at this line:
> 
> ```python
> ax.scatter(x, y, color=point_color, alpha=alpha, marker='o')
> ```
> 
> where the circular markers are drawn as bezier curves and call `numpy.roots()` to solve a small matrix problem to find the bounding box of those curves. So if my analysis is correct here, what you have is a problem with your build of matplotlib or numpy, not contourpy. You could confirm this by commenting out the `ax.scatter` line above and the test that caused the bus error should no longer do so and the test should fail instead because the output PNG will be different. But the test suite should complete without a crash.
> 
> The next experiment to try would be to replace the `ax.scatter` line with
> 
> ```python
> ax.plot(x, y, color=point_color, alpha=alpha, marker='o', lw=0)
> ```
> 
> which generates exactly the same output (on common platforms!) but uses an entirely different code path in C++ rather than the Python code that calls `numpy.root`.
> 
> I am going to change the `ax.scatter` to `ax.plot` anyway as I think it is a better option and should be marginally faster.

OK, I can test that tomorrow in case you don't have the time to try it yourself now.

**Comment by glaubitz** [comment]
This works now and `contourpy` 1.0.7 builds fine on sparc64: https://buildd.debian.org/status/fetch.php?pkg=contourpy&arch=sparc64&ver=1.0.7-1&stamp=1708124804&raw=0
